version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: assignment_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=assignment123
      - MYSQL_DATABASE=workshop
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=grafana123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./assignment_dataset.sql:/docker-entrypoint-initdb.d/assignment_dataset.sql
    command: --default-authentication-plugin=mysql_native_password

  grafana:
    image: grafana/grafana:latest
    container_name: assignment_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - mysql

  influxdb:
    image: influxdb:2.7
    container_name: assignment_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=assignment
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=assignment-token-123
    volumes:
      - influxdb_data:/var/lib/influxdb2

  node-red:
    image: nodered/node-red:latest
    container_name: assignment_node_red
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    depends_on:
      - mysql
      - influxdb

volumes:
  mysql_data:
  grafana_data:
  influxdb_data:
  node_red_data: